# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-01"

[[extensions]]
type = "ui_extension"
name = "checkout-ui-first"
handle = "checkout-ui-first"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Banner.jsx"
target = "purchase.checkout.block.render"

[[extensions.targeting.metafields]]
namespace = "checkout_title"
key = "title"

[[extensions.targeting.metafields]]
namespace = "checkout_text"
key = "text"

[[extensions.targeting.metafields]]
namespace = "checkout_image"
key = "image"

[[extensions.targeting]]
module = "./src/Protect.jsx"
target = "purchase.checkout.cart-line-list.render-after"

[[extensions.targeting.metafields]]
namespace = "checkout_protect"
key = "product"

[[extensions.targeting]]
module = "./src/ProductLineItem.jsx"
target = "purchase.checkout.cart-line-item.render-after"

[[extensions.targeting.metafields]]
namespace = "checkout_product_line"
key = "line"

[[extensions.targeting]]
module = "./src/ShippingFields.jsx"
target = "purchase.checkout.shipping-option-list.render-after"

[[extensions.targeting.metafields]]
namespace = "checkout_order"
key = "instructionp"

[[extensions.targeting.metafields]]
namespace = "checkout_order"
key = "date"

[[extensions.targeting]]
module = "./src/MightLike.jsx"
target = "purchase.checkout.header.render-after"

[[extensions.targeting.metafields]]
namespace = "checkout_might_like"
key = "products"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
